
dataset:
  mean: [0.4914, 0.4822, 0.4465]
  std:  [0.2023, 0.1994, 0.2010]
  root: /content/drive/MyDrive/cifar_project/datasets
  num_classes: 10
  classes: [plane, car, bird, cat, deer, dog, frog, horse, ship, truck]

training:
  batch_size: 64
  test_batch_size: 128
  epochs: 30
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005
  seed: 42

model:
  name: resnet18
